services:
  api:
    image: ghcr.io/hieudoan7/knowledgehub-api:latest
    container_name: knowledgehub-api
    environment:
      AWS_SHARED_CREDENTIALS_FILE: /app/.aws/credentials
      AWS_CONFIG_FILE: /app/.aws/config
      AWS_EC2_METADATA_DISABLED: "true"

    env_file:
      - ./deploy/.env.prod

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped
    volumes:
      - ~/.aws/credentials:/app/.aws/credentials:ro
      - ~/.aws/config:/app/.aws/config:ro

  postgres:
    image: pgvector/pgvector:pg17
    container_name: knowledgehub-postgres

    environment:
      POSTGRES_DB: knowledgehub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d knowledgehub"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

volumes:
  postgres_data:
