services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: knowledgehub-api

    environment:
      ENV_FILE: .env.docker

    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app
      - backend_venv:/app/.venv

    depends_on:
      - postgres

    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg17

    container_name: knowledgehub-postgres

    environment:
      POSTGRES_DB: knowledgehub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data:
  backend_venv:

