from fastapi.testclient import TestClient


def test_register_user(client: TestClient) -> None:
    """A new user can register successfully."""

    payload = {
        "email": "john@example.com",
        "password": "Password123!",
        "full_name": "John Doe",
    }

    response = client.post(
        "/api/v1/auth/register",
        json=payload,
    )

    assert response.status_code == 201

    body = response.json()

    assert body["email"] == payload["email"]
    assert body["full_name"] == payload["full_name"]

    # Generated by the server
    assert "id" in body
    assert "created_at" in body
    assert "updated_at" in body


def test_register_duplicate_email(client: TestClient) -> None:
    """Registering the same email twice should fail."""

    payload = {
        "email": "duplicate@example.com",
        "password": "Password123!",
        "full_name": "John Doe",
    }

    first = client.post(
        "/api/v1/auth/register",
        json=payload,
    )

    assert first.status_code == 201

    second = client.post(
        "/api/v1/auth/register",
        json=payload,
    )

    assert second.status_code == 409

    assert second.json() == {
        "detail": "User with email 'duplicate@example.com' already exists."
    }

