MAX_EMAIL_LENGTH = 255
MAX_NAME_LENGTH = 255
MAX_PASSWORD_HASH_LENGTH = 255
PASSWORD_MAX_LENGTH = 128
PASSWORD_MIN_LENGTH = 8

ACCESS_TOKEN_TYPE = "access"
REFRESH_TOKEN_TYPE = "refresh"

TOKEN_TYPE_CLAIM = "type"
SUBJECT_CLAIM = "sub"

AUTH_SCHEME = "Bearer"
